set_T *rules = set_init(rule_cmp_generic);symbol_T *program =  init_symbol_non_terminal(init_non_terminal("program", NON_TERM_program));
set_add(rules, program);
symbol_T *statement =  init_symbol_non_terminal(init_non_terminal("statement", NON_TERM_statement));
set_add(rules, statement);
symbol_T *expression_statement =  init_symbol_non_terminal(init_non_terminal("expression_statement", NON_TERM_expression_statement));
set_add(rules, expression_statement);
symbol_T *expression =  init_symbol_non_terminal(init_non_terminal("expression", NON_TERM_expression));
set_add(rules, expression);
symbol_T *assignment_expression =  init_symbol_non_terminal(init_non_terminal("assignment_expression", NON_TERM_assignment_expression));
set_add(rules, assignment_expression);
symbol_T *assignment_operator =  init_symbol_non_terminal(init_non_terminal("assignment_operator", NON_TERM_assignment_operator));
set_add(rules, assignment_operator);
symbol_T *unary_operator =  init_symbol_non_terminal(init_non_terminal("unary_operator", NON_TERM_unary_operator));
set_add(rules, unary_operator);
symbol_T *conditional_expression =  init_symbol_non_terminal(init_non_terminal("conditional_expression", NON_TERM_conditional_expression));
set_add(rules, conditional_expression);
symbol_T *logical_or_expression =  init_symbol_non_terminal(init_non_terminal("logical_or_expression", NON_TERM_logical_or_expression));
set_add(rules, logical_or_expression);
symbol_T *logical_and_expression =  init_symbol_non_terminal(init_non_terminal("logical_and_expression", NON_TERM_logical_and_expression));
set_add(rules, logical_and_expression);
symbol_T *inclusive_or_expression =  init_symbol_non_terminal(init_non_terminal("inclusive_or_expression", NON_TERM_inclusive_or_expression));
set_add(rules, inclusive_or_expression);
symbol_T *exclusive_or_expression =  init_symbol_non_terminal(init_non_terminal("exclusive_or_expression", NON_TERM_exclusive_or_expression));
set_add(rules, exclusive_or_expression);
symbol_T *and_expression =  init_symbol_non_terminal(init_non_terminal("and_expression", NON_TERM_and_expression));
set_add(rules, and_expression);
symbol_T *equality_expression =  init_symbol_non_terminal(init_non_terminal("equality_expression", NON_TERM_equality_expression));
set_add(rules, equality_expression);
symbol_T *relational_expression =  init_symbol_non_terminal(init_non_terminal("relational_expression", NON_TERM_relational_expression));
set_add(rules, relational_expression);
symbol_T *shift_expression =  init_symbol_non_terminal(init_non_terminal("shift_expression", NON_TERM_shift_expression));
set_add(rules, shift_expression);
symbol_T *additive_expression =  init_symbol_non_terminal(init_non_terminal("additive_expression", NON_TERM_additive_expression));
set_add(rules, additive_expression);
symbol_T *multiplicative_expression =  init_symbol_non_terminal(init_non_terminal("multiplicative_expression", NON_TERM_multiplicative_expression));
set_add(rules, multiplicative_expression);
symbol_T *cast_expression =  init_symbol_non_terminal(init_non_terminal("cast_expression", NON_TERM_cast_expression));
set_add(rules, cast_expression);
symbol_T *unary_expression =  init_symbol_non_terminal(init_non_terminal("unary_expression", NON_TERM_unary_expression));
set_add(rules, unary_expression);
symbol_T *postfix_expression =  init_symbol_non_terminal(init_non_terminal("postfix_expression", NON_TERM_postfix_expression));
set_add(rules, postfix_expression);
symbol_T *primary_expression =  init_symbol_non_terminal(init_non_terminal("primary_expression", NON_TERM_primary_expression));
set_add(rules, primary_expression);
symbol_T *identifier =  init_symbol_non_terminal(init_non_terminal("identifier", NON_TERM_identifier));
set_add(rules, identifier);
symbol_T *constant =  init_symbol_non_terminal(init_non_terminal("constant", NON_TERM_constant));
set_add(rules, constant);
symbol_T *compound_statement =  init_symbol_non_terminal(init_non_terminal("compound_statement", NON_TERM_compound_statement));
set_add(rules, compound_statement);
symbol_T *declaration =  init_symbol_non_terminal(init_non_terminal("declaration", NON_TERM_declaration));
set_add(rules, declaration);
symbol_T *declaration_specifier =  init_symbol_non_terminal(init_non_terminal("declaration_specifier", NON_TERM_declaration_specifier));
set_add(rules, declaration_specifier);
symbol_T *type_specifier =  init_symbol_non_terminal(init_non_terminal("type_specifier", NON_TERM_type_specifier));
set_add(rules, type_specifier);
symbol_T *type_qualifier =  init_symbol_non_terminal(init_non_terminal("type_qualifier", NON_TERM_type_qualifier));
set_add(rules, type_qualifier);
symbol_T *init_declarator =  init_symbol_non_terminal(init_non_terminal("init_declarator", NON_TERM_init_declarator));
set_add(rules, init_declarator);
symbol_T *selection_statement =  init_symbol_non_terminal(init_non_terminal("selection_statement", NON_TERM_selection_statement));
set_add(rules, selection_statement);
symbol_T *iteration_statement =  init_symbol_non_terminal(init_non_terminal("iteration_statement", NON_TERM_iteration_statement));
set_add(rules, iteration_statement);
symbol_T *jump_statement =  init_symbol_non_terminal(init_non_terminal("jump_statement", NON_TERM_jump_statement));
set_add(rules, jump_statement);
symbol_T *labeled_statement =  init_symbol_non_terminal(init_non_terminal("labeled_statement", NON_TERM_labeled_statement));
set_add(rules, labeled_statement);
symbol_T *declarator =  init_symbol_non_terminal(init_non_terminal("declarator", NON_TERM_declarator));
set_add(rules, declarator);
symbol_T *init_declarator_list =  init_symbol_non_terminal(init_non_terminal("init_declarator_list", NON_TERM_init_declarator_list));
set_add(rules, init_declarator_list);
symbol_T *initializer =  init_symbol_non_terminal(init_non_terminal("initializer", NON_TERM_initializer));
set_add(rules, initializer);
symbol_T *initializer_list =  init_symbol_non_terminal(init_non_terminal("initializer_list", NON_TERM_initializer_list));
set_add(rules, initializer_list);
symbol_T *constant_expression =  init_symbol_non_terminal(init_non_terminal("constant_expression", NON_TERM_constant_expression));
set_add(rules, constant_expression);
