#ifndef NON_TERM 
#define NON_TERM(name, symbol) 
#endif 

NON_TERM(null, "") 
NON_TERM(start, "S'") 

NON_TERM(program, "program")
NON_TERM(statement, "statement")
NON_TERM(expression_statement, "expression_statement")
NON_TERM(expression, "expression")
NON_TERM(assignment_expression, "assignment_expression")
NON_TERM(assignment_operator, "assignment_operator")
NON_TERM(unary_operator, "unary_operator")
NON_TERM(conditional_expression, "conditional_expression")
NON_TERM(logical_or_expression, "logical_or_expression")
NON_TERM(logical_and_expression, "logical_and_expression")
NON_TERM(inclusive_or_expression, "inclusive_or_expression")
NON_TERM(exclusive_or_expression, "exclusive_or_expression")
NON_TERM(and_expression, "and_expression")
NON_TERM(equality_expression, "equality_expression")
NON_TERM(relational_expression, "relational_expression")
NON_TERM(shift_expression, "shift_expression")
NON_TERM(additive_expression, "additive_expression")
NON_TERM(multiplicative_expression, "multiplicative_expression")
NON_TERM(cast_expression, "cast_expression")
NON_TERM(unary_expression, "unary_expression")
NON_TERM(postfix_expression, "postfix_expression")
NON_TERM(primary_expression, "primary_expression")
NON_TERM(identifier, "identifier")
NON_TERM(constant, "constant")
NON_TERM(compound_statement, "compound_statement")
NON_TERM(declaration, "declaration")
NON_TERM(declaration_specifier, "declaration_specifier")
NON_TERM(type_specifier, "type_specifier")
NON_TERM(type_qualifier, "type_qualifier")
NON_TERM(init_declarator, "init_declarator")
NON_TERM(selection_statement, "selection_statement")
NON_TERM(iteration_statement, "iteration_statement")
NON_TERM(jump_statement, "jump_statement")
NON_TERM(labeled_statement, "labeled_statement")
NON_TERM(declarator, "declarator")
NON_TERM(init_declarator_list, "init_declarator_list")
NON_TERM(initializer, "initializer")
NON_TERM(initializer_list, "initializer_list")
NON_TERM(constant_expression, "constant_expression")

#undef NON_TERM